[build]
  command = "npm run build"
  publish = "dist"
  # environment variables can be set in Netlify UI if needed

# Optional: pretty 404 handling â€” uncomment if you have SPA routes
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
